import os

get = os.environ.get

TOKEN                 = get("SNITCHVIS_TOKEN")
TESTING               = get("SNITCHVIS_TESTING", True)
TESTING_GUILDS        = [get("SNITCHVIS_TESTING_GUILD")] if get("SNITCHVIS_TESTING_GUILD", None) else []
AUTHOR_ID             = get("SNITCHVIS_AUTHOR_ID")
COMMAND_LOG_CHANNEL   = get("SNITCHVIS_COMMAND_LOG_CHANNEL")
JOIN_LOG_CHANNEL      = get("SNITCHVIS_JOIN_LOG_CHANNEL")
ERROR_LOG_CHANNEL     = get("SNITCHVIS_ERROR_LOG_CHANNEL")
LIVEMAP_LOG_CATEGORY  = get("SNITCHVIS_LIVEMAP_LOG_CATEGORY")
DEFAULT_PREFIX        = get("SNITCHVIS_DEFAULT_PREFIX", ".")
KIRA_ID               = get("SNITCHVIS_KIRA_ID", 952325487663939645)
